version: '3'
services:
  app:
    container_name: maven-redis
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-server
  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
